import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import jason_crop from "../public/jason_crop.png";
import aws from "../public/aws.png";
import aws_associate from "../public/aws_associate.png";
import wsu from "../public/wsu.png";
import views from "../public/views.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import web7 from "../public/web7.png";
import web8 from "../public/web8.png";
import { useState, useEffect } from "react";


function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [pageViews, setPageViews] = useState(0);

  useEffect(() => {
    fetch('https://owdnky6qb1.execute-api.us-west-2.amazonaws.com/Prod/webvisits',{
      method: 'POST'
    })
    .then(response => response.json())
    .then((response) => {
      console.log(response.body);
    })

    fetch(
      "https://owdnky6qb1.execute-api.us-west-2.amazonaws.com/Prod/webvisits"
    )
      .then((res) => res.json())
      .then((data) => {
        setPageViews(data.body.count);
        console;
      });
    
    
    }, []);


  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jasons Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Jason Ruiz</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-2xl"
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              {/* <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li> */}
              {/* <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Matching Game
                </a>
              </li> */}
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Jason Ruiz
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">
              Full Stack Software Engineer and Cloud Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
              Passionate about creating modern web applications in the cloud,
              reading, and contributing to a team effort through Volleyball.
              Looking to connect with employers that need help modernizing their
              applications into the cloud to minimize infrastructure costs.
              Experienced in learning new technologies, express, Django, React,
              JavaScript, C#, Python, MySQL, and AWS cloud.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://www.linkedin.com/in/jason-ruiz-028561177/">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/jasonaruiz95">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative flex justify-center mt-20">
            <Image
              src={jason_crop}
              alt="profile pic"
              width={600}
              height={600}
              className="flex justify-center "
            />
          </div>
        </section>

        {/* Second Page */}
        <section>
          <div>
            <h3 className="text-3xl py-1 ">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Ive worked in the IT industry for the past 5 years and am looking
              to breakout into my first Software Engineering role. I have had
              work experience with Server and platform operations within
              Telecommunications where I worked with VMWare to create highly
              available systems for Production and Development environments. I
              have experience creating a modern web application using cloud
              technology. The benefits to using cloud can include low cost, low
              system maintenance, while not sacrificing reliability. This
              website is being hosted using serverless options within AWS Cloud
              including an S3 Bucket, AWS Lambda Functions, API Gateway, and
              CloudFront distribution.
            </p>
          </div>
          <div className="lg:flex gap-10 ">
          <div className="text-center shadow-lg p-10 rounded-xl my-10 justify-center dark:bg-white">
              <Image
                src={aws}
                alt="aws"
                width={200}
                height={200}
                className="flex justify-center mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                AWS Cloud Practitioner
              </h3>
              <p className="py-2">
                Completed the AWS Cloud Practitioner Exam in April of 2023.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 justify-center dark:bg-white">
              <Image
                src={aws_associate}
                alt="aws"
                width={200}
                height={200}
                className="flex justify-center mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                AWS Solutions Architect Associate
              </h3>
              <p className="py-2">
                Completed the AWS Solutions Architect Associate Exam in April of 2023.
              </p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 justify-center dark:bg-white">
              <Image
                alt="wsu logo"
                src={wsu}
                width={200}
                height={200}
                className="flex justify-center mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Bachelors Degree of Computer Science
              </h3>
              <p className="py-2">
                Graduating from Weber State University in August 2023 with a
                degree in Computer Science. Maintained a GPA of 3.5
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 justify-center dark:bg-white">
              <Image
                alt="page views"
                src={views}
                width={200}
                height={200}
                className="flex justify-center mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Page Views</h3>
              <p id="counter" className="py-2">
                {pageViews}
              </p>
            </div>
          </div>
        </section>

        {/* Third Section */}
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Ive worked on various different projects over the years which
              will be showcased here.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                alt=""
                src={web1}
                className="rounded-lg object-cover"
                width={"100"}
                height={"100"}
                layout="responsive"
              ></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt=""
                src={web2}
                className="rounded-lg object-cover"
                width={"100"}
                height={"100"}
                layout="responsive"
              ></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt=""
                src={web3}
                className="rounded-lg object-cover"
                width={"100"}
                height={"100"}
                layout="responsive"
              ></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt=""
                src={web4}
                className="rounded-lg object-cover"
                width={"100"}
                height={"100"}
                layout="responsive"
              ></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt=""
                src={web5}
                className="rounded-lg object-cover"
                width={"100"}
                height={"100"}
                layout="responsive"
              ></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt=""
                src={web6}
                className="rounded-lg object-cover"
                width={"100"}
                height={"100"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt=""
                src={web7}
                className="rounded-lg object-cover"
                width={"100"}
                height={"100"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt=""
                src={web8}
                className="rounded-lg object-cover"
                width={"100"}
                height={"100"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

export default Home;
